"""empty message

Revision ID: bbdbea7ae773
Revises: f2425c2a2f3e
Create Date: 2025-05-04 00:09:18.346020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdbea7ae773'
down_revision = 'f2425c2a2f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planetas', ['planeta_id'], ['planeta_id'])

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_constraint('planetas_personaje_id_fkey', type_='foreignkey')
        batch_op.drop_column('personaje_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planetas_personaje_id_fkey', 'personajes', ['personaje_id'], ['personaje_id'])

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###
