"""empty message

Revision ID: f2425c2a2f3e
Revises: 5e2252ee0f6a
Create Date: 2025-04-25 18:14:47.918901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2425c2a2f3e'
down_revision = '5e2252ee0f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_planeta_id_fkey', type_='foreignkey')
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('personajes_planeta_id_fkey', 'planetas', ['planeta_id'], ['planeta_id'])

    # ### end Alembic commands ###
